export enum GameTab {
  START_MENU = "START_MENU",
  SINGLE_PLAYER_CONFIG = "SINGLE_PLAYER_CONFIG",
  MULTI_PLAYER_CONFIG = "MULTI_PLAYER_CONFIG",
  KNIFFEL_GAME = "KNIFFEL_GAME",
  RESULT = "RESULT",
}
